# Generated by Django 3.2.6 on 2021-10-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gotasks', '0002_auto_20211005_1649'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cards',
            unique_together={('card_name', 'list')},
        ),
        migrations.AlterUniqueTogether(
            name='lists',
            unique_together={('list_name', 'project')},
        ),
    ]
