# Generated by Django 3.2.6 on 2021-10-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gotasks', '0003_auto_20211006_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lists',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
