# Generated by Django 3.2.6 on 2021-08-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('moderator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('project_wiki', models.CharField(max_length=250)),
                ('project_created', models.DateTimeField(auto_now_add=True)),
                ('project_members', models.ManyToManyField(to='gotasks.Members')),
            ],
            options={
                'ordering': ['project_created'],
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=100)),
                ('list_created', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotasks.projects')),
            ],
            options={
                'ordering': ['list_created'],
            },
        ),
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('assigned', models.ManyToManyField(to='gotasks.Members')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gotasks.lists')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
